<a href="https://colab.research.google.com/github/Cl8D/Python-Data-Analysis-Image-Processing/blob/main/04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **04강. Numpy의 연산과 함수**

In [4]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2, 2)
print(array)
print("--")
result_array = array * 10
print(result_array)

[[2 7]
 [7 1]]
--
[[20 70]
 [70 10]]


In [5]:
import numpy as np

array1 = np.arange(4).reshape(2, 2)
print(array1)
print("--")
array2 = np.arange(2)
print(array2)
print("--")
array3 = array1 + array2

print(array3)

[[0 1]
 [2 3]]
--
[0 1]
--
[[0 2]
 [2 4]]


In [6]:
import numpy as np

array1 = np.arange(0, 8).reshape(2, 4)
print(array1)
print("--")
array2 = np.arange(0, 8).reshape(2, 4)
print(array2)
print("--")
array3 = np.concatenate([array1, array2], axis=0) #위, 아래로 합치기
print(array3)
print("--")
array4 = np.arange(0, 4).reshape(4, 1)
print(array4)
print("--")

print(array3 + array4)

[[0 1 2 3]
 [4 5 6 7]]
--
[[0 1 2 3]
 [4 5 6 7]]
--
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
--
[[0]
 [1]
 [2]
 [3]]
--
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [7]:
import numpy as np

# 반복문을 이용할 때보다 매우 빠름.
# 이미지 처리(Image Processing)에서 자주 활용
array1 = np.arange(16).reshape(4, 4)
print(array1)
print("--")
array2 = array1 < 10
print(array2)
print("--")
array1[array2] = 100 #조건에 만족하는 데이터(True)만 100으로 바꾸는 것을 처리. 
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
--
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [8]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


In [9]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print(array)
print("합계:", np.sum(array, axis=0)) #행방향으로 합치기

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계: [24 28 32 36]
