<a href="https://colab.research.google.com/github/Cl8D/Python-Data-Analysis-Image-Processing/blob/main/03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**03강. Numpy의 기본 사용법**

In [1]:
import numpy as np

array = np.array([1, 2, 3])
print(array.size) #배열의 크기
print(array.dtype) #배열 원소의 타입
print(array[2]) #인덱스 2의 원소

3
int64
3


In [4]:
#0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

#0으로 초기화
array2 = np.zeros((4, 4), dtype = float)
print(array2)

#1로 초기화
array3 = np.ones((3, 3), dtype = str)
print(array3)

#0부터 9까지 랜덤하게 초기화된 배열 만들기
array4 = np.random.randint(0, 10, (3, 3))
print(array4)

#평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[4 7 6]
 [4 8 7]
 [3 9 7]]
[[ 0.84377664  0.52552309 -0.22351411]
 [ 0.61645865  0.43928408  0.04441804]
 [ 1.22231377  0.84850922 -0.07125703]]


In [6]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [8]:
array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape(2, 2) #2x2 형태의 배열로 바꾸기

print(array2.shape)

(2, 2)


In [11]:
array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)

array3 = np.concatenate([array1, array2], axis = 0)
print(array3)
print(array3.shape)

[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]
(3, 4)


In [20]:
array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [1], axis = 1)

print(array)
print(left) #왼쪽 부분
print(right) #오른쪽 부분

print(left.shape)
print(right.shape)
print(right[1][1])

[[0 1 2 3]
 [4 5 6 7]]
[[0]
 [4]]
[[1 2 3]
 [5 6 7]]
(2, 1)
(2, 3)
6
