<a href="https://colab.research.google.com/github/Cl8D/Python-Data-Analysis-Image-Processing/blob/main/05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **05강. Numpy의 활용**

In [5]:
import numpy as np

# 단일 객체 저장 및 불러오기
array = np.arange(0, 10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

!ls

[0 1 2 3 4 5 6 7 8 9]
sample_data  saved.npy	saved.npz


In [6]:
import numpy as np

# 복수 객체 저장 및 불러오기
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

!ls

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
sample_data  saved.npy	saved.npz


In [12]:
import numpy as np

array = np.array([5, 9, 10, 3, 1])
print(array)
print("--")

# 오름차순 정렬
array.sort()
print(array)
print("--")

# 내림차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array[::-1]) #거꾸로 출력
print("--")

# 열을 기준으로 정렬
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
print(array)
print("--")


array.sort(axis=0) #더 큰 행이 아래쪽으로 가도록 출력
print(array)

[ 5  9 10  3  1]
--
[ 1  3  5  9 10]
--
[10  9  5  3  1]
--
[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
--
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [15]:
import numpy as np

# 균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5)
print(array)
print("--")

# 난수의 재연(실행마다 결과 동일)
np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))
print("--")

# 배열 객체 복사
array1 = np.arange(0, 10)
print(array1)
array2 = array1.copy()
print(array2)
print("--")

# 중복된 원소 제거
array = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))

[ 0.   2.5  5.   7.5 10. ]
--
[[4 9 6]
 [3 3 7]]
--
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
--
[1 2 3]
